Dev
keyjin88/go-loyalty-system pull request #1
Opened 2023-07-10 19:56 UTC by keyjin88

2023-07-12 14:37 UTC, maxlyaptsev requested changes

2023-07-12 14:37 UTC, maxlyaptsev commented on cmd/gophermart/main.go
> +	logger.Log.Panic(server.Start())
предлагаю сделать graceful shutdown
- Что будет если отправили запрос, приняли его, сохранили заказ в бд, и сразу после этого завершили приложение? Скорее всего клиент получит ошибку. Но в бд мы данные уже положили
- Что происходит с конектом к бд когда мы резко завершаем приложение, не закрыв соединение?

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/handlers/order.go
> +		case err.Error() == "order already uploaded by this user":
лучше создать ошибку как экспортируемую переменню и сравнивать с ней через 
```go
var ErrOrderAlreadyUploaded
//...
if errors.Is(err, ErrOrderAlreadyUploaded) {
}
```

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/handlers/users.go
> +		} else {
лишний else

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/handlers/users.go
> +	userFromDB, err := h.userService.GetUserByUserName(req)
используются одни и те же данные для разных слоев. Проблема может возникнуть когда в запрос захочется добавить что-то (или убрать) и сервис который вроде бы не связан может пострадать

Да, кажется немного излишней работой, но так делают очень часто - иметь две структуры -одна для реквеста, другая для сервиса. И из одной в другую перекладываются данные.

Если данные требуют преобразований и большого кода, например перекладывания списокв, выделяют в отедльный пакет - builders, который просто собирает нужные структуры из других

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/services/update_order_worker.go
> +				logger.Log.Infof("Failed to process order %v: %v", order.ID, err)
а почему info лог? у нас же произошла ошибка

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/services/update_order_worker.go
> +		go func(order storage.Order) {
количество горутин никак не ограничивается. Если придет много заказов то мы займем всю доступную мощьности и сервис будет долго отвечать т.к. не останется ресурсов на другую работу

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/setup.go
> +	orderProcessingChannel := make(chan storage.Order)
т.к. канал не буферезированный, он будет блокироваться пока не прочитаем из него
Можно попробовать провести небольшое нагрузочное тестирование и проверить как будет отличаться RPS в зависимости от размера буфера

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/services/update_order_worker.go
> +				savedUser.Balance += order.Accrual
Такое изменение не устойчиво к асинхронным запросам - если вызвать паралельно несколько, то данные будут не определены (зависит от уровня изоляции). Лучше передавать diff аргументом, а в базе данных делать += Это самый безопасный способ.

2023-07-12 14:37 UTC, maxlyaptsev commented on internal/app/services/withdraw.go
> +	user.Withdrawn += request.Sum
Простой пример - в текущий момент в коде
- у пользователя на балансе 1000 рублей, списываем 200
- пока обрабатывали, с момента получения баланса, пользователь получил баллы за предыдущий заказ, еще 500
- после апдейта мы не получим новые баллы, запишем 1000 - 200 = 800

2023-07-13 09:31 UTC, keyjin88 commented on internal/app/services/update_order_worker.go
> +				savedUser.Balance += order.Accrual
Не совсем понял, что именно нужно делать. Переделал так, чтобы в горутине извлекались актуальные данные о заказе и повысил уровень изоляции запросов транзакции до SERIALIZABLE. Если не то сделал, то нужна пояснительная бригада.

2023-07-13 10:08 UTC, keyjin88 commented on internal/app/services/withdraw.go
> +	user.Withdrawn += request.Sum
Реализовал на основе мьютексов, но не уверен, что это оптимально и правильно. Если совсем трешак, то давай созвонимся - расскажешь, как лучше к многопоточке подступаться, а то я в Java давно привык что она вся под капотом. Ну или накидай ссылок, где можно вдумчиво почитать.

2023-07-13 18:59 UTC, maxlyaptsev commented on internal/app/services/update_order_worker.go
> +				savedUser.Balance += order.Accrual
имел ввиду что такая запись избавляет от многих проблем: update users set balance = balance + $1 
такое изменение атомарно
Просто пока дойдем до сохренения баланс может уже измениться
SERIALIZABLE доставит проблемы с отменой транзакции, нужно уметь их повторять

2023-07-13 19:01 UTC, maxlyaptsev commented on internal/app/services/update_order_worker.go
> +				savedUser.Balance += order.Accrual
Вообще вопрос наверное немного за рамками курса. Часто для таких операций ставят явную блокировку например на пользователя или на баланс - прям в ручке. Я говорил что работал в платежном процессинге, видимо из-за этого повышенная чувствительность к таким вещам. При мне из-за простых косяков компания теряла миллионы за считанные минуты

2023-07-13 19:06 UTC, maxlyaptsev commented on internal/app/services/withdraw.go
> +	user.Withdrawn += request.Sum
Самый простой вариант - в другом коменте написал - сразу в запросе изменять суммы

2023-07-13 20:24 UTC, maxlyaptsev commented on internal/app/services/withdraw.go
> +	user.Withdrawn += request.Sum
мьютексы не совсем то решение. Как и в предыдущем комментарии - вместо явной блокировки можно использовать атомарное изменение записи (update users set balance = balance + $1)

2023-07-13 20:24 UTC, maxlyaptsev approved these changes

2023-07-17 12:33 UTC, merged